server:
  port: 9000

management:
  endpoint:
    beans:
      cache:
        time-to-live: 10s

info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
  java:
    souce: @java.version@
    target: @java.version@


spring:
  application:
    name: consumer-1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9110/eureka/
  instance:
    prefer-ip-address: true
